worker_processes  1;

events {
    worker_connections  1024;
}

http {
    upstream backend_v1 {
        server 127.0.0.1:3000;
        server 127.0.0.1:3001;
    }

    upstream backend_v2 {
        server 127.0.0.1:4000;
        server 127.0.0.1:4001;
    }

    server {
        listen 8080;

        location /api/v1/ {
            proxy_pass http://backend_v1;
        }

        location /api/v2/ {
            proxy_pass http://backend_v2;
        }

        location / {
            return 200 "NGINX WORKING\n";
        }
    }
}
